# Generated by Django 5.0.1 on 2026-01-05 20:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_beratung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personenbezogenedaten',
            name='grad_der_behinderung',
            field=models.IntegerField(blank=True, help_text='Grad der Behinderung (0-100 is the system used in germany)', null=True, validators=[django.core.validators.MinValueValidator(0, message='GdB muss mindestens 0 sein'), django.core.validators.MaxValueValidator(100, message='GdB darf höchstens 100 sein')]),
        ),
        migrations.CreateModel(
            name='FolgenDerGewalt',
            fields=[
                ('folge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kategorie', models.CharField(choices=[('PSYCHISCH', 'Psychisch'), ('KOERPERLICH', 'Körperlich'), ('DAUERHAFT', 'Dauerhaft'), ('FINANZIELL', 'Finanziell')], max_length=20)),
                ('ist_unterkategorie', models.BooleanField(default=False)),
                ('beschreibung', models.TextField(blank=True)),
                ('hauptkategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unterkategorien', to='core.folgendergewalt')),
            ],
            options={
                'verbose_name': 'Folge der Gewalt',
                'verbose_name_plural': 'Folgen der Gewalt',
                'db_table': 'folgen_der_gewalt',
                'ordering': ['kategorie', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GewalttatArt',
            fields=[
                ('art_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ist_unterkategorie', models.BooleanField(default=False)),
                ('beschreibung', models.TextField(blank=True)),
                ('hauptkategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unterkategorien', to='core.gewalttatart')),
            ],
            options={
                'verbose_name': 'Gewalttat Art',
                'verbose_name_plural': 'Gewalttat Arten',
                'db_table': 'gewalttat_art',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fall_FolgenDerGewalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weitere_informationen', models.TextField(blank=True)),
                ('fall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folgen_relations', to='core.fall')),
                ('folge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.folgendergewalt')),
            ],
            options={
                'verbose_name': 'Fall-Folge Verknüpfung',
                'verbose_name_plural': 'Fall-Folge Verknüpfungen',
                'db_table': 'fall_folgen_der_gewalt',
                'unique_together': {('fall', 'folge')},
            },
        ),
    ]
