# Generated by Django 5.0.1 on 2026-01-06 09:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_personenbezogenedaten_grad_der_behinderung_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gewalttat',
            fields=[
                ('gewalttat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alter_zum_zeitpunkt_der_tat', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('alter_tat_keine_angabe', models.BooleanField(default=False)),
                ('zeitraum_von', models.DateField(blank=True, null=True)),
                ('zeitraum_bis', models.DateField(blank=True, null=True)),
                ('zeitraum_keine_angabe', models.BooleanField(default=False)),
                ('zahl_der_vorfaelle', models.CharField(blank=True, choices=[('EINMALIG', 'einmalig'), ('MEHRERE', 'mehrere'), ('GENAUE_ZAHL', 'genaue Zahl'), ('KEINE_ANGABE', 'keine Angabe')], max_length=20, null=True)),
                ('zahl_der_vorfaelle_genau', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('anzahl_taeterinnen', models.CharField(blank=True, choices=[('1', '1'), ('MEHRERE', 'mehrere'), ('GENAUE_ZAHL', 'genaue Zahl'), ('KEINE_ANGABE', 'keine Angabe')], max_length=20, null=True)),
                ('anzahl_taeterinnen_genau', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('taeterinnen_details', models.JSONField(blank=True, default=list, help_text='Array of objects with geschlecht and verhaeltnis_zur_ratsuchenden_person')),
                ('art_der_gewalt_andere_details', models.TextField(blank=True)),
                ('tatort', models.CharField(blank=True, choices=[('LEIPZIG', 'Leipzig'), ('LEIPZIG_LAND', 'Leipzig Land'), ('NORDSACHSEN', 'Nordsachsen'), ('SACHSEN', 'Sachsen'), ('DEUTSCHLAND', 'Deutschland'), ('AUSLAND', 'Ausland'), ('AUF_DER_FLUCHT', 'auf der Flucht'), ('IM_HERKUNFTSLAND', 'im Herkunftsland'), ('KEINE_ANGABE', 'keine Angabe')], max_length=30, null=True)),
                ('anzeige', models.CharField(blank=True, choices=[('JA', 'Ja'), ('NEIN', 'Nein'), ('NOCH_NICHT_ENTSCHIEDEN', 'noch nicht entschieden'), ('KEINE_ANGABE', 'keine Angabe')], max_length=30, null=True)),
                ('medizinische_versorgung', models.CharField(blank=True, choices=[('JA', 'Ja'), ('NEIN', 'Nein'), ('KEINE_ANGABE', 'keine Angabe')], max_length=20, null=True)),
                ('vertrauliche_spurensicherung', models.CharField(blank=True, choices=[('JA', 'Ja'), ('NEIN', 'Nein'), ('KEINE_ANGABE', 'keine Angabe')], max_length=20, null=True)),
                ('mitbetroffene_kinder', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('davon_direkt_betroffen', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('gewalt_notizen', models.TextField(blank=True)),
                ('fall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gewalttaten', to='core.fall')),
            ],
            options={
                'verbose_name': 'Gewalttat',
                'verbose_name_plural': 'Gewalttaten',
                'db_table': 'gewalttat',
                'ordering': ['-zeitraum_von'],
            },
        ),
        migrations.CreateModel(
            name='Gewalttat_GewalttatArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andere_details', models.TextField(blank=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gewalttatart')),
                ('gewalttat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gewalttat')),
            ],
            options={
                'verbose_name': 'Gewalttat-Art Verknüpfung',
                'verbose_name_plural': 'Gewalttat-Art Verknüpfungen',
                'db_table': 'gewalttat_gewalttat_art',
            },
        ),
        migrations.AddIndex(
            model_name='gewalttat',
            index=models.Index(fields=['fall', 'zeitraum_von'], name='gewalttat_fall_id_b8c619_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gewalttat_gewalttatart',
            unique_together={('gewalttat', 'art')},
        ),
    ]
