# Generated by Django 5.0.1 on 2026-01-06 12:36

import core.validators.json_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gewalttat_gewalttat_gewalttatart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gewalttat',
            name='taeterinnen_details',
            field=models.JSONField(blank=True, default=list, help_text='Array of objects with geschlecht and verhaeltnis_zur_ratsuchenden_person', validators=[core.validators.json_validators.validate_taeterinnen_details]),
        ),
        migrations.AlterField(
            model_name='personenbezogenedaten',
            name='grad_der_behinderung',
            field=models.IntegerField(blank=True, help_text='Grad der Behinderung (0-100 is the system used in Germany)', null=True, validators=[django.core.validators.MinValueValidator(0, message='GdB muss mindestens 0 sein'), django.core.validators.MaxValueValidator(100, message='GdB darf höchstens 100 sein')]),
        ),
    ]
