# Generated by Django 5.0.1 on 2026-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_gewalttat_taeterinnen_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gewalttat',
            name='gewalttat_arten',
            field=models.ManyToManyField(blank=True, help_text='Violence types linked via junction table Gewalttat_GewalttatArt', related_name='gewalttaten', through='core.Gewalttat_GewalttatArt', to='core.gewalttatart'),
        ),
    ]
