# Generated by Django 6.0.2 on 2026-02-04 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assign_erweitert_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionset',
            options={'verbose_name': 'Permission Set', 'verbose_name_plural': 'Permission Sets'},
        ),
        migrations.AddField(
            model_name='fall',
            name='folgen_der_gewalt',
            field=models.ManyToManyField(blank=True, help_text='Consequence types linked via junction table Fall_FolgenDerGewalt', related_name='faelle', through='core.Fall_FolgenDerGewalt', to='core.folgendergewalt'),
        ),
        migrations.AlterField(
            model_name='permissionset',
            name='can_assign_roles',
            field=models.BooleanField(default=False, help_text='Erlaubt das Zuweisen und Ändern von Benutzerrollen'),
        ),
        migrations.AlterField(
            model_name='permissionset',
            name='can_delete_cases',
            field=models.BooleanField(default=False, help_text='Erlaubt das Archivieren von Fällen (Soft Delete)'),
        ),
        migrations.AlterField(
            model_name='permissionset',
            name='can_edit_cases',
            field=models.BooleanField(default=False, help_text='Erlaubt das Erstellen und Bearbeiten von Fällen, Beratungen und Gewalttaten'),
        ),
        migrations.AlterField(
            model_name='permissionset',
            name='can_hard_delete_cases',
            field=models.BooleanField(default=False, help_text='Erlaubt das permanente Löschen von Fällen (Hard Delete mit CASCADE)'),
        ),
        migrations.AlterField(
            model_name='permissionset',
            name='can_manage_reference_data',
            field=models.BooleanField(default=False, help_text='Erlaubt das Hinzufügen und Bearbeiten von GewalttatArt und FolgenDerGewalt'),
        ),
        migrations.AlterField(
            model_name='permissionset',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Erlaubt das Erstellen, Bearbeiten und Löschen von Benutzern'),
        ),
        migrations.AlterField(
            model_name='permissionset',
            name='can_view_cases',
            field=models.BooleanField(default=False, help_text='Erlaubt das Anzeigen von Fällen'),
        ),
        migrations.CreateModel(
            name='Anfrage',
            fields=[
                ('anfrage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wie', models.CharField(choices=[('EMAIL', 'E-Mail'), ('TELEFON', 'Telefon'), ('ANDERE', 'andere')], max_length=20, verbose_name='Kontaktweg')),
                ('datum_anfrage', models.DateField(verbose_name='Datum der Anfrage')),
                ('anfrage_aus', models.CharField(choices=[('LEIPZIG_STADT', 'Leipzig Stadt'), ('LEIPZIG_LAND', 'Leipzig Land'), ('NORDSACHSEN', 'Nordsachsen'), ('SACHSEN', 'Sachsen'), ('ANDERE', 'andere')], max_length=20, verbose_name='Anfrage aus')),
                ('wer_hat_angefragt', models.CharField(choices=[('F', 'Fachkraft'), ('A', 'Angehörige:r'), ('B', 'Betroffene:r'), ('ANONYM', 'anonym'), ('QB', 'queer Betroffene:r'), ('QF', 'queer Fachkraft'), ('QA', 'queer Angehörige:r'), ('Q_ANONYM', 'queer anonym'), ('FFB', 'Fachkraft für Betroffene'), ('AFB', 'Angehörige:r für Betroffene'), ('FFQB', 'Fachkraft für queere Betroffene'), ('AFQB', 'Angehörige für queere Betroffene')], max_length=20, verbose_name='Wer hat angefragt')),
                ('art_der_anfrage', models.CharField(choices=[('MEDIZINISCHE_SOFORTHILFE', 'Medizinische Soforthilfe'), ('VERTRAULICHE_SPURENSICHERUNG', 'Vertrauliche Spurensicherung'), ('BERATUNGSBEDARF', 'Beratungsbedarf'), ('ZU_RECHTLICHEN', 'zu Rechtlichen'), ('SONSTIGES', 'Sonstiges')], max_length=40, verbose_name='Art der Anfrage')),
                ('termin_vergeben', models.BooleanField(default=False, verbose_name='Termin vergeben')),
                ('termin_datum', models.DateField(blank=True, null=True, verbose_name='Datum des Termins')),
                ('termin_ort', models.CharField(blank=True, choices=[('LEIPZIG_STADT', 'Leipzig Stadt'), ('LEIPZIG_NORD', 'Leipzig Nord'), ('NORDSACHSEN', 'Nordsachsen')], max_length=20, verbose_name='Ort des Termins')),
                ('erstellungsdatum', models.DateTimeField(auto_now_add=True)),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_anfragen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anfrage',
                'verbose_name_plural': 'Anfragen',
                'db_table': 'anfrage',
                'ordering': ['-datum_anfrage'],
                'indexes': [models.Index(fields=['datum_anfrage'], name='anfrage_datum_a_2a0c2c_idx'), models.Index(fields=['anfrage_aus'], name='anfrage_anfrage_04720d_idx')],
            },
        ),
    ]
