# Generated by Django 6.0.2 on 2026-02-17 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_anfrage_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSurveyQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('double', 'Double'), ('date', 'Date')], max_length=25)),
            ],
            options={
                'verbose_name': 'Frage für Fall',
                'verbose_name_plural': 'Fragen für Fall',
                'db_table': 'case_survey_question',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='CaseSurveyAnswer',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='core.fall')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.casesurveyquestion')),
            ],
            options={
                'verbose_name': 'Antwort für Fall',
                'verbose_name_plural': 'Antworten für Fall',
                'db_table': 'case_survey_answer',
                'unique_together': {('case', 'question')},
            },
        ),
    ]
