# Generated by Django 6.0.2 on 2026-02-17

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_survey_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatsPreset",
            fields=[
                ("preset_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("scope", models.CharField(choices=[("PERSONAL", "Persönlich"), ("GLOBAL", "Für alle")], default="PERSONAL", max_length=20)),
                ("is_system", models.BooleanField(default=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_stats_presets", to=settings.AUTH_USER_MODEL)),
                ("owner", models.ForeignKey(blank=True, help_text="Owner for personal presets. Must be null for GLOBAL presets.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="stats_presets", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Statistik-Preset",
                "verbose_name_plural": "Statistik-Presets",
                "db_table": "stats_preset",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="statspreset",
            index=models.Index(fields=["scope", "name"], name="stats_prese_scope_e88871_idx"),
        ),
        migrations.AddIndex(
            model_name="statspreset",
            index=models.Index(fields=["owner", "name"], name="stats_prese_owner__7e0a34_idx"),
        ),
        migrations.AddConstraint(
            model_name="statspreset",
            constraint=models.UniqueConstraint(fields=("scope", "owner", "name"), name="uniq_stats_preset_name_per_scope_owner"),
        ),
    ]

