# Generated by Django 6.0.2 on 2026-02-17

from django.db import migrations


def create_default_presets(apps, schema_editor):
    StatsPreset = apps.get_model("core", "StatsPreset")

    # Shipped default presets:
    # One per Beratungsstelle, based on common requirements from the "Statistische Angaben..."
    # (Punkt 3+) and the internal Statistik-Bogen.
    default_modules = [
        {"key": "cases_total"},
        {"key": "consultations_total"},
        {"key": "clients_by_wohnort"},
        {"key": "clients_by_staatsangehoerigkeit"},
        {"key": "clients_by_rolle"},
        {"key": "clients_by_geschlecht"},
        {"key": "consultations_by_durchfuehrungsart"},
        {"key": "consultations_by_durchfuehrungsort"},
        {"key": "inquiries_total"},
    ]

    presets = [
        ("System: Statistik FBS 1 (Leipzig Stadt, queer)", "FBS_1_LE"),
        ("System: Statistik FBS 2 (Landkreis Nordsachsen)", "FBS_2_LKNSA"),
        ("System: Statistik FBS 3 (Landkreis Leipzig)", "FBS_3_LKLE"),
    ]

    for name, beratungsstelle in presets:
        StatsPreset.objects.get_or_create(
            scope="GLOBAL",
            owner=None,
            name=name,
            defaults={
                "is_system": True,
                "payload": {
                    "filters": {
                        "zustaendige_beratungsstelle": [beratungsstelle],
                        # default: only active cases
                        "include_archived": False,
                    },
                    "modules": default_modules,
                },
            },
        )


def remove_default_presets(apps, schema_editor):
    StatsPreset = apps.get_model("core", "StatsPreset")
    StatsPreset.objects.filter(
        scope="GLOBAL",
        owner=None,
        is_system=True,
        name__startswith="System: Statistik FBS",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_stats_preset_model"),
    ]

    operations = [
        migrations.RunPython(create_default_presets, remove_default_presets),
    ]

