# Generated by Django 6.0.2 on 2026-02-17 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_default_stats_presets'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistikPreset',
            fields=[
                ('preset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
                ('filter_config', models.JSONField(default=dict)),
                ('ist_global', models.BooleanField(default=False, help_text='Visible to all users if True')),
                ('ist_system_preset', models.BooleanField(default=False, editable=False, help_text='System-provided preset, cannot be deleted')),
                ('erstellungsdatum', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statistik Preset',
                'verbose_name_plural': 'Statistik Presets',
                'db_table': 'statistik_preset',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='statspreset',
            new_name='stats_prese_scope_406aaf_idx',
            old_name='stats_prese_scope_e88871_idx',
        ),
        migrations.RenameIndex(
            model_name='statspreset',
            new_name='stats_prese_owner_i_9a68b3_idx',
            old_name='stats_prese_owner__7e0a34_idx',
        ),
        migrations.AddField(
            model_name='statistikpreset',
            name='erstellt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistik_presets', to=settings.AUTH_USER_MODEL),
        ),
    ]
