# Generated by Django 6.0.2 on 2026-02-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_statistikpreset_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statspreset',
            name='stats_prese_scope_406aaf_idx',
        ),
        migrations.RemoveIndex(
            model_name='statspreset',
            name='stats_prese_owner_i_9a68b3_idx',
        ),
        migrations.RemoveConstraint(
            model_name='statspreset',
            name='uniq_stats_preset_name_per_scope_owner',
        ),
        migrations.DeleteModel(
            name='StatsPreset',
        ),
    ]
