# Generated by Django 5.2.8 on 2025-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
                ('edit_date', models.DateField()),
                ('edited_by_employee', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
