# Generated by Django 5.2.8 on 2025-12-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
