# Generated by Django 5.2.8 on 2025-12-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_case_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='edit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='edited_by_employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
