# Generated by Django 5.0.1 on 2026-01-05 15:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionset',
            name='can_hard_delete_cases',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Fall',
            fields=[
                ('fall_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zustaendige_beratungsstelle', models.CharField(choices=[('FBS_1_LE', 'Fachberatungsstelle für queere Betroffene von sexualisierter Gewalt in der Stadt Leipzig'), ('FBS_2_LKNSA', 'Fachberatung gegen sexualisierte Gewalt im Landkreis Nordsachsen'), ('FBS_3_LKLE', 'Fachberatung gegen sexualisierte Gewalt im Landkreis Leipzig')], max_length=20)),
                ('erstellungsdatum', models.DateField(auto_now_add=True)),
                ('letzte_bearbeitung', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AKTIV', 'Aktiv'), ('ARCHIVIERT', 'Archiviert')], default='AKTIV', max_length=20)),
                ('ist_vollstaendig', models.BooleanField(default=False)),
                ('ist_abgeschlossen', models.BooleanField(default=False)),
                ('abschlussdatum', models.DateTimeField(blank=True, null=True)),
                ('beratungsanzahl', models.IntegerField(default=0)),
                ('letzte_beratung', models.DateField(blank=True, null=True)),
                ('informationsquelle', models.CharField(blank=True, choices=[('POLIZEI', 'Selbstmeldungen über Polizei'), ('PRIVATE_KONTAKTE', 'Private Kontakte'), ('BERATUNGSSTELLEN', 'Beratungsstellen'), ('INTERNET', 'Internet'), ('AEMTER', 'Ämter'), ('GESUNDHEITSWESEN', 'Gesundheitswesen (Arzt/Ärztin)'), ('RECHTSANWAELTE', 'Rechtsanwälte/-anwältinnen'), ('ANDERE', 'andere Quelle'), ('KEINE_ANGABE', 'keine Angabe')], max_length=30, null=True)),
                ('informationsquelle_andere_details', models.TextField(blank=True)),
                ('anzahl_dolmetschungen_stunden', models.FloatField(default=0.0)),
                ('dolmetschung_sprachen', models.TextField(blank=True)),
                ('weitere_notizen', models.TextField(blank=True)),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bearbeitete_faelle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fall',
                'verbose_name_plural': 'Fälle',
                'db_table': 'fall',
                'ordering': ['-erstellungsdatum'],
            },
        ),
        migrations.CreateModel(
            name='PersonenbezogeneDaten',
            fields=[
                ('personenbezogene_daten_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(db_index=True, max_length=64, unique=True)),
                ('rolle_der_ratsuchenden_person', models.CharField(choices=[('BETROFFENE', 'Betroffene:r'), ('ANGEHOERIGE', 'Angehörige:r'), ('FACHKRAFT', 'Fachkraft')], max_length=20)),
                ('alter', models.IntegerField(blank=True, null=True)),
                ('alter_keine_angabe', models.BooleanField(default=False)),
                ('geschlechtsidentitaet', models.CharField(blank=True, choices=[('CIS_W', 'cis weiblich'), ('CIS_M', 'cis männlich'), ('TRANS_W', 'trans weiblich'), ('TRANS_M', 'trans männlich'), ('TRANS_NB', 'trans nicht binär'), ('INTER', 'inter'), ('AGENDER', 'agender'), ('DIVERS', 'divers'), ('KEINE_ANGABE', 'keine Angabe')], max_length=20, null=True)),
                ('sexualitaet', models.CharField(blank=True, choices=[('LESBISCH', 'lesbisch'), ('SCHWUL', 'schwul'), ('BISEXUELL', 'bisexuell'), ('ASEXUELL', 'asexuell'), ('HETEROSEXUELL', 'heterosexuell'), ('KEINE_ANGABE', 'keine Angabe')], max_length=20, null=True)),
                ('wohnort', models.CharField(blank=True, choices=[('LEIPZIG_STADT', 'Leipzig Stadt'), ('LEIPZIG_LAND', 'Leipzig Land'), ('NORDSACHSEN', 'Nordsachsen'), ('SACHSEN', 'Sachsen'), ('DEUTSCHLAND', 'Deutschland'), ('ANDERE', 'andere'), ('KEINE_ANGABE', 'keine Angabe')], max_length=20, null=True)),
                ('wohnort_details', models.TextField(blank=True)),
                ('staatsangehoerigkeit_deutsch', models.CharField(blank=True, choices=[('DEUTSCH', 'deutsch'), ('NICHT_DEUTSCH', 'nicht deutsch')], max_length=20, null=True)),
                ('staatsangehoerigkeit_land', models.CharField(blank=True, max_length=100)),
                ('berufliche_situation', models.CharField(blank=True, choices=[('ARBEITSLOS', 'arbeitslos'), ('STUDIEREND', 'studierend'), ('BERUFSTAETIG', 'berufstätig'), ('BERENTET', 'berentet'), ('AZUBI', 'Azubi'), ('BERUFSUNFAEHIG', 'berufsunfähig'), ('KEINE_ANGABE', 'keine Angabe')], max_length=30, null=True)),
                ('schwerbehinderung', models.CharField(blank=True, choices=[('JA', 'Ja'), ('NEIN', 'Nein')], max_length=10, null=True)),
                ('form_der_behinderung', models.CharField(blank=True, choices=[('KOGNITIV', 'kognitiv'), ('KOERPERLICH', 'körperlich')], max_length=20)),
                ('grad_der_behinderung', models.IntegerField(blank=True, help_text='Grad der Behinderung (0-100, German system)', null=True, validators=[django.core.validators.MinValueValidator(0, message='GdB muss mindestens 0 sein'), django.core.validators.MaxValueValidator(100, message='GdB darf höchstens 100 sein')])),
                ('personenbezogene_notizen', models.TextField(blank=True)),
                ('fall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personenbezogene_daten', to='core.fall')),
            ],
            options={
                'verbose_name': 'Personenbezogene Daten',
                'verbose_name_plural': 'Personenbezogene Daten',
                'db_table': 'personenbezogene_daten',
            },
        ),
        migrations.AddIndex(
            model_name='fall',
            index=models.Index(fields=['erstellungsdatum'], name='fall_erstell_da8988_idx'),
        ),
        migrations.AddIndex(
            model_name='fall',
            index=models.Index(fields=['zustaendige_beratungsstelle'], name='fall_zustaen_aa5650_idx'),
        ),
    ]
