# Generated by Django 5.0.1 on 2026-01-05 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permissionset_can_hard_delete_cases_fall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beratung',
            fields=[
                ('beratung_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datum', models.DateField()),
                ('durchfuehrungsart', models.CharField(choices=[('PERSOENLICH', 'persönlich'), ('VIDEO', 'video'), ('TELEFON', 'telefon'), ('AUFSUCHEND', 'aufsuchend'), ('SCHRIFTLICH', 'schriftlich')], max_length=20)),
                ('durchfuehrungsort', models.CharField(choices=[('LEIPZIG_STADT', 'Leipzig Stadt'), ('LEIPZIG_LAND', 'Leipzig Land'), ('NORDSACHSEN', 'Nordsachsen')], max_length=20)),
                ('weitere_notizen', models.TextField(blank=True)),
                ('fall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beratungen', to='core.fall')),
            ],
            options={
                'verbose_name': 'Beratung',
                'verbose_name_plural': 'Beratungen',
                'db_table': 'beratung',
                'ordering': ['-datum'],
                'indexes': [models.Index(fields=['fall', 'datum'], name='beratung_fall_id_67fe6e_idx')],
            },
        ),
    ]
